sudo: required
services:
- docker
before_install:
- docker pull node:8-onbuild
install:
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
- docker run --rm probot-hello npm run lint
deploy:
  provider: heroku
  api_key:
    secure: "Cx/PJ5q5Damw+KQcRLNgom8xGJzUtFYnPb3nXmJOn7ZQZ7NE+BvBOoBnsnEbeEBAyVI9WHdWlCf68He5Ibxk+GjE4FRmvfD3pB8ly1kGuzHrEGos8lnfNauz7ib13GAqGKfHdEQm6NjjXQc2lgK0QJkbTwdNWBF5M79Nchizq5ly7/gQKSTpbdWXIcOoY7Y8KzHkHKML4AjXk1Ggm+vgWc/WCqp1imHkWzgOxujgKxJN+XLyWe/1ADABIgbNAUjRVtywhPlfGSGhAwCkiNaIHQPtQ3obw/bDhfYnnCW/DUqcPLj97Slc2WgQBBFy7hmLenCO7vBM0ypAMZ0t8Q993z7yfkAeiCDe6PIjF3sJaIsJeIwhgqBFt+Hf7B6H0kjrKWEJMN2YUdb0wN9Fx9w20nXZZ01n5ZHJAMHk/weawL98tOHZGNDpbRnsqL5KF3Vek+8SPNQNgAfSuombx7JITs2EaOYdJUogevcG4cSa6WKPsj8jt1jEL8F51r8BL1G4Zo/SF2JvxcC5er66/Iw8baUSYz7/lVUUmTWAurOHe/zzcySei7BCODpuneIhIv2QDn/IDQdky60+XYpQlMzpygo9bOmHBwuzjc3+tI1tOCT1ffQC5wSFgP93fqSMYsLEZ7wz0OeAdNPx5UYOqAHMqITQZHj1/KXhgzPgTpYNsqQ="
  on: heroku_production
  app: probot-pablo-asencio
